# Generated by Django 5.1.6 on 2025-03-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='need',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='occupation',
        ),
    ]
