# Generated by Django 5.1.6 on 2025-03-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_beneficiary_gender_beneficiary_need_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='need',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='occupation',
        ),
    ]
